# Generated by Django 5.1.1 on 2024-10-18 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detalle', '0001_initial'),
        ('pedido', '0002_remove_pedido_estado'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaPreparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('En espera', 'En espera'), ('En preparación', 'En preparación'), ('Terminado', 'Terminado')], default='En preparación', max_length=20)),
                ('cantidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='detalle.detallepedido')),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedido.pedido')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.producto')),
            ],
        ),
    ]
