# Generated by Django 5.1.1 on 2024-10-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonaPreparacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonapreparacion',
            name='estado',
            field=models.CharField(choices=[('En espera', 'En espera'), ('Terminado', 'Terminado')], default='En espera', max_length=50),
        ),
    ]
