# Generated by Django 5.1.1 on 2024-10-18 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('observaciones', models.TextField(max_length=500)),
                ('estado', models.CharField(choices=[('En espera', 'En espera'), ('Terminado', 'Terminado')], default='En espera', max_length=50)),
                ('option', models.CharField(choices=[('para llevar', 'Para llevra'), ('consumir', 'Consumir')], default='Para Llevar', max_length=50)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.producto')),
            ],
        ),
    ]
