# Generated by Django 5.1.1 on 2024-10-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_remove_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='observaciones',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
