# Generated by Django 5.1.1 on 2024-10-18 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detalle', '0001_initial'),
        ('facturacion', '0001_initial'),
        ('pedido', '0003_alter_pedido_observaciones'),
        ('producto', '0001_initial'),
        ('zonaPreparacion', '0002_alter_zonapreparacion_estado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetallePedido',
            new_name='Detalle',
        ),
    ]
